### ISSUE TITLE
Empty output for BAM+rMats

### ISSUE THREAD

**Issue by Qingru44004** [nf-core/rnasplice#105]
### Description of the bug

Hi, I passed the test samples. But when I run on my samples (BAM+rMats). I got empty rMats output. There was no error reported, showing completed.

### Command used and terminal output

```console
$ nextflow run software/rnasplice -profile docker --input nf_samplesheet.csv --contrasts nf_contrastsheet.csv --genome GRCh38 --outdir myenv
```

### Relevant files

[nextflow.log](https://github.com/nf-core/rnasplice/files/13568032/nextflow.log)
[nextflow.config.log](https://github.com/nf-core/rnasplice/files/13568127/nextflow.config.log)

**Comment by jma1991** [comment]
Hey @Qingru44004 

Please could you provide the stdout and stderr files produced by the various rMATS processes? Once we have those, we can examine what might have gone wrong.

Best,
James

**Comment by jma1991** [comment]
Stale issue, please re-open if you are still experiencing problems.
