### ISSUE TITLE
DEXSeq-DTU Stager pScreenAdjusted

### ISSUE THREAD

**Issue by bio-info-guy** [nf-core/rnasplice#108]
### Description of the bug

I have a question regarding a parameter in the stager screening procedure:
**/bin/run_stager.R** 
**line 147:**
```
object <- stageRTx(
    pScreen         = output[["pScreen"]],
    pConfirmation   = output[["pConfirmation"]],
    tx2gene         = output[["tx2gene"]],
    pScreenAdjusted = FALSE
)
```
Why is pScreenAdjusted set to FALSE, I thought that the perGeneQvalue outputed by DEXseq is already adjusted, as described by the function helper in DEXSeq, which would mean the parameter should be set to TRUE here. This is also set to TRUE in the original workflow proposed in:
https://f1000research.com/articles/7-952/v3

**Comment by jma1991** [comment]
Hello @bio-info-guy 

You are absolutely correct, we've just generated a new release (v1.0.2) with the fix.

Thanks,
James
