### ISSUE TITLE
sashimi_plot error

### ISSUE THREAD

**Issue by GimenaA** [nf-core/rnasplice#111]
### Description of the bug

I'm getting an error message when running rnasplice about the sashimi_plot. The error message is copied below:

-[nf-core/rnasplice] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI (3)'

Caused by:
  Process `NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI (3)` terminated with an error exit status (1)

Command executed:

  sashimi_plot --plot-event ENSG00000147403 index miso_settings.txt --output-dir sashimi
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI":
      python: $(python --version | sed "s/Python //g")
      misopy: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('misopy').version)")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  /usr/local/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: The mpl_toolkits.axes_grid module was deprecated in version 2.1. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist provies the same functionality instead.
    warnings.warn(message, mplDeprecation, stacklevel=1)
  Traceback (most recent call last):
    File "/usr/local/bin/sashimi_plot", line 11, in <module>
      sys.exit(main())
    File "/usr/local/lib/python2.7/site-packages/misopy/sashimi_plot/sashimi_plot.py", line 276, in main
      plot_label=plot_label)
    File "/usr/local/lib/python2.7/site-packages/misopy/sashimi_plot/sashimi_plot.py", line 142, in plot_event
      %(event_name, pickle_dir)
  Exception: Event ENSG00000147403 not found in pickled directory index. Are you sure this is the right directory for the event?

### Command used and terminal output

```console
This is the command I ran:
nextflow run nf-core/rnasplice -profile docker -params-file params.yaml

This was my params.yaml file:
input: '/path/samplesheet.csv'
contrasts: '/path/contrastsheet.csv'
outdir: '/path/outdir/'
source: 'fastq'
genome: 'BDGP6'
aligner: 'star_salmon'
save_reference: true
dexseq_dtu: true
min_samps_gene_expr: 6
min_gene_expr: 10
min_samps_feature_expr: 3
min_feature_expr: 10
min_samps_feature_prop: 3
min_feature_prop: 0.1

This was my Contrastsheet:
contrast,treatment,control
AUB_CS,AUB,CS
```

### System information

Nextflow version: version 23.10.0
Linux OS
Version of nf-core/rnasplice 1.0.1

**Comment by jma1991** [comment]
Hey @GimenaA 

The default gene identifier in the config is an example of a gene from the human genome. You are using a Drosophila melanogaster genome, therefore please provide a gene found in that genome.

Thanks,
James

**Comment by GimenaA** [comment]
Thank you!

**Comment by GimenaA** [comment]
I still get the same error when I run it with gene identifiers from the Drosophila melanogaster genome. I added the following parameters to my params file from above:
sashimi_plot: true
miso_genes: FBgn0002121
skip_bigwig: false

Also when I run it with this 3 additional parameters, I don't get the dexseq_dtu folder or my trimimport folder even though I still have my "dexseq_dtu: true" parameter. Can you tell me why that is?

THANK YOU

**Comment by gowgowuk** [comment]
Hello, I got a identical error. I am working with human but we found out that probabaly the source of the error is the fact that the pickle index include ensembl gene id version. So, original .command.sh 

```
#!/bin/bash -euo pipefail
sashimi_plot --plot-event ENSG00000004961 index miso_settings.txt --output-dir sashimi

cat <<-END_VERSIONS > versions.yml
"NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI":
    python: $(python --version | sed "s/Python //g")
    misopy: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('misopy').version)")
END_VERSIONS

```

When I manually add in the version like this it works:
`sashimi_plot --plot-event ENSG00000004961.15 index miso_settings.txt --output-dir sashimi` did work

How can I get this to work without manually editing every single gene?

Thanks
