### ISSUE TITLE
The processes for splitting files are running very slowly with large numbers of input samples

### ISSUE THREAD

**Issue by amizeranschi** [nf-core/rnasplice#120]
Hello,

We are attempting to run this pipeline with a rather complex scenario: 850 contrasts and 3400 samples. The processes `SPLIT_FILES_TPM`, `SPLIT_FILES_IOE` and `SPLIT_FILES_IOI` appear to be running very slowly. 

For example, looking at `SPLIT_FILES_TPM`, this has been running for 12 hours and only produced 61 TPM files so far. At this rate, it should take around 4 weeks to finish this process, before even attempting to run Suppa2...

We have successfully run these samples through `nf-core/rnaseq` (which took less than a week on 512 cores and 2 TB of RAM), and `nf-core/differentialabundance` (which only took 2 hours to run DESeq2). We now intend to run Suppa2 via this pipeline.

Any advice for speeding things up would be much appreciated. This is the command that we are running:

```
nextflow run nf-core/rnasplice -r 1.0.2 -c custom.config -params-file params.yml --igenomes_ignore --genome null \
--input /path/to/sample-sheet-rnasplice.csv \
--outdir run-rnasplice -profile docker --source salmon_results \
--fasta /path/to/genome/gencode_v45_spike-ins.fasta \
--gtf /path/to/genome/gencode_v45_spike-ins.gtf \
--star_index /path/to/genome/index/star \
--salmon_index /path/to/genome/index/salmon \
--dexseq_exon false --dexseq_dtu false \
--suppa --suppa_per_local_event \
--contrasts /path/to/contrasts-rnasplice.csv \
--sashimi_plot false
```

**Comment by jma1991** [comment]
Hey @amizeranschi 

I think I have a solution for you and it should be fairly easy to implement. The suppa_split_file.R script contains a function which selects columns from the count matrix for each condition, however for some strange reason it [reads in the count matrix within the function](https://github.com/zifornd/rnasplice/blob/112231ce1ff7572aa10c64ce16c0f56c950dde58/bin/suppa_split_file.R#L75). Therefore, when we iterate over the conditions and call the function it reads in the count matrix again and again. If I move this line out of the function it should speed up dramatically. I'll have a hot fix for to try tomorrow.

**Comment by amizeranschi** [comment]
Hi @jma1991 

Yes, that R script seems to be the bottleneck. Please let me know when you'll have the commit ready and I'll be happy to test it over the week-end.

**Comment by jma1991** [comment]
Hi @amizeranschi 

I've opened a PR with the hot fix, please have a look and test on your samples.

**Comment by jma1991** [comment]
Glad to hear it is working - I'll release v1.0.3 this week so you should have a proper release to reference. Keep an eye out for the release announcement.
