### ISSUE TITLE
Merged genes output

### ISSUE THREAD

**Issue by SergioManzano10** [nf-core/rnasplice#139]
### Description of the bug

When I run the rnasplice pipeline and I get the result about differential exon usage, I get a table of counts.

I have used the ENSEMBL files (fasta and gtf) to generate the sashimi plots. However, when I look at the counts table mentioned above, for some genes (like BRCA1) I get "merged" identifiers (e.g. ENSG00000267002+ENSG00000012048), so I don't know the exon counts that correspond to each gen.

I think it is due to overlapping positions.

How could I solve it?

Thank you.

**Comment by jma1991** [comment]
You are correct; the merged identifiers are generated when there are overlapping exons. You can find the exon-level counts in the featurecounts directory. Additionally, these counts are available in the DGEList object from the edgeR analysis and the DEXSeqDataSet object from the DEXSeq analysis.

**Comment by SergioManzano10** [comment]
Is the same if I set the  - - aggregate parameter to false?

**Comment by SergioManzano10** [comment]
I did with - - aggregate parameter set to false and worked.

I will close the issue.
