### ISSUE TITLE
Implement IsoformSwitchAnalyzeR

### ISSUE THREAD

**Issue by jesseangelis** [nf-core/rnasplice#148]
### Description of feature

IsoformSwitchAnalyzeR is a powerful tool for identifying isoform switches in transcript data. It would allow the end user to analyze and visualize isoform switches. 

My colleague discussed with you on 15 February on Slack that we should write a pull request for IsoformSwitchAnalyzeR if we want to include it in the pipeline. This is the issue for that enhancement.

**Comment by jesseangelis** [comment]
As there is a lot of code for a new tool, I am happy to help with the code review.

**Comment by jma1991** [comment]
Hi Jesse,

I just wanted to give you a heads-up in case you haven't seen it—I’ve assigned three reviewers to your pull request. We’ll do our best to get this merged as quickly as possible. Apologies again for the long delay, and thanks for your patience!
