### ISSUE TITLE
Miso ERROR

### ISSUE THREAD

**Issue by torres-HI** [nf-core/rnasplice#150]
### Description of the bug

Hi,

I have same error with MISO plotting

I read that the issue is the notation of the reference genome.
My question is what will be the best reference genome for work with mouse.
am used ENSEMBL 38, because is suppose it has all the annotated transcript, at difference of UCSC that is better for epigenomic issues (atac, chip-seq, etc) but not have the transcript annotation.

I also saw the default file  (params.json)keeps elements that do not belong to the specie I use, such as ENS in humano descriptors. Deleting them generates the same error

I need to mach the splicing + rna expression and atac-seq

I'm listening suggestion, thank you

### Command used and terminal output

```console
nextflow run nf-core/rnasplice --input manifest10h.csv  --contrasts contrast.csv  --outdir $OUTDIR\
         --genome GRCm38\
         --save_reference\
         -profile singularity  -resume genM38  -r 1.0.4

ERROR ~ Error executing process > 'NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI (2)'

Caused by:
  Process `NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI (2)` terminated with an error exit status (1)


Command executed:

  sashimi_plot --plot-event ENSG00000005302 index miso_settings.txt --output-dir sashimi

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNASPLICE:RNASPLICE:VISUALISE_MISO:MISO_SASHIMI":
      python: $(python --version | sed "s/Python //g")
      misopy: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('misopy').version)")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)
```

### Relevant files

 "sashimi_plot": true,
    "miso_genes": "ENSG00000004961, ENSG00000005302, ENSG00000147403",
    "miso_genes_file": null,
    "miso_read_len": 75,
    "fig_width": 7,

**Comment by jma1991** [comment]
Hi @torres-HI,

Since you're using GRCm38 as your reference genome, you'll need to use gene identifiers from the corresponding annotation, like those from Ensembl. By default, the pipeline is set up for human identifiers, but you can adjust the configuration to match the identifiers relevant to your sample’s genome. Could you give it a try with a few mouse gene identifiers from Ensembl and let me know if you run into any issues?

**Comment by torres-HI** [comment]
Hi thank you for your response, as I say, there are the defaul paramenter, which generate the problem. Not sure how to eliminate it. I was delete it from the file  params_2024-08-23_05-38-17.json., but when run again, send to you again the Id from human. 
there is not my file.
Also I would like to ask when I can fin a file with the AS from mice for add to the process. thank you

**Comment by torres-HI** [comment]
hi, thank you for your response, here are the next error using mouse ID.
Plus 43 more processes waiting for tasks…
-[nf-core/rnasplice] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_RNASPLICE:RNASPLICE:DEXSEQ_DEU:DEXSEQ_ANNOTATION (genes.gtf)'

Caused by:
  Process `NFCORE_RNASPLICE:RNASPLICE:DEXSEQ_DEU:DEXSEQ_ANNOTATION (genes.gtf)` terminated with an error exit status (1)


Command executed:

  dexseq_prepare_annotation.py genes.gtf DEXSeq.gff

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNASPLICE:RNASPLICE:DEXSEQ_DEU:DEXSEQ_ANNOTATION":
      htseq: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('htseq').version)")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  Traceback (most recent call last):
    File "/home/torres91/.nextflow/assets/nf-core/rnasplice/bin/dexseq_prepare_annotation.py", line 132, in <module>
      raise ValueError("Same name found on two strands: %s, %s" % (str(l[i]), str(l[i + 1])))
  ValueError: Same name found on two strands: <GenomicFeature: exonic_part 'Gm4312+Gm4301' at chr10: 100366498 -> 100367412 (strand '+')>, <GenomicFeature: exo>

Work dir:
  /mnt/lustre/koa/scratch/torres91/Roman/splice/work/82/ace1a4d5faed55765d2215a31dbf9f

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details


thank for your help

**Comment by jma1991** [comment]
Hi @torres-HI 

Could you please share your nextflow.log file along with the nextflow.config file from your latest run? This information would really help me in troubleshooting the issue.

Thanks a lot!

**Comment by torres-HI** [comment]
Hi thanks

I send you some of the files request.
I use the default file as template to avoid code problems, just change the ID values
[params_mm10_trans.json](https://github.com/user-attachments/files/16806460/params_mm10_trans.json)
[splice_job_error_geneID.txt](https://github.com/user-attachments/files/16806464/splice_job_error_geneID.txt)
[splice_job_error_transID.txt](https://github.com/user-attachments/files/16806465/splice_job_error_transID.txt)

I was testing to used refSeq from Ensembl and entrez (UCSC mm10) using Id from genes, and transcripts, but the error is the same.

not sure where will be the problem.
thnak for your help

**Comment by torres-HI** [comment]
<img width="753" alt="Screenshot 2024-08-29 at 12 13 49" src="https://github.com/user-attachments/assets/b8932c00-9d09-499b-92de-bd37ea7d9753">

**Comment by jma1991** [comment]
Hi @torres-HI,

I was looking through your log files and noticed that you're specifying Ensembl gene identifiers for use with MISO, but the reference genome you have downloaded is based on the UCSC gene annotation. This will lead to mismatches. Here's the relevant part of your log file:

```
Reference genome options
  genome                : mm10
  fasta                 : s3://ngi-igenomes/igenomes//Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa
  gtf                   : s3://ngi-igenomes/igenomes//Mus_musculus/UCSC/mm10/Annotation/Genes/genes.gtf
  star_index            : s3://ngi-igenomes/igenomes//Mus_musculus/UCSC/mm10/Sequence/STARIndex/
  save_reference        : true
  igenomes_base         : s3://ngi-igenomes/igenomes/
```

To avoid any issues, please make sure to use the correct gene identifiers that match the reference genome you're working with.

**Comment by torres-HI** [comment]
Hi again. thnak you for your time and reply.

but I said, I have 2 weeks with the same error, am change the refSeq using ensembl or entrez, and also change ID-genes or ID-transcripts. the error in all the cases is the same.

do you have some ideas how to fix it?

is just the last part, and the param.json that keep the default items in each run to everyone

by the way, why we need the ID when we are looking for all the possibles alternative splicing?

thank you.

**Comment by torres-HI** [comment]
here is the last one:
Reference genome options
  genome                : mm10
  fasta                 : s3://ngi-igenomes/igenomes//Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa
  gtf                   : s3://ngi-igenomes/igenomes//Mus_musculus/UCSC/mm10/Annotation/Genes/genes.gtf
  star_index            : s3://ngi-igenomes/igenomes//Mus_musculus/UCSC/mm10/Sequence/STARIndex/
  save_reference        : true
  igenomes_base         : s3://ngi-igenomes/igenomes/

Alignment options
  aligner               : star_salmon

rMATS options
  rmats                 : true

DEXSeq DEU options
  dexseq_exon           : true

edgeR DEU options
  edger_exon            : true

DEXSeq DTU options
  dexseq_dtu            : true
  min_samps_gene_expr   : 4
  min_samps_feature_expr: 2
  min_samps_feature_prop: 2

Miso
  sashimi_plot          : true
  miso_genes            : ENSMUST00000105541.7,ENSMUST00000006787.7


ERROR ~ Error executing process > 'NFCORE_RNASPLICE:RNASPLICE:DEXSEQ_DEU:DEXSEQ_ANNOTATION (genes.gtf)'

Caused by:
  Process `NFCORE_RNASPLICE:RNASPLICE:DEXSEQ_DEU:DEXSEQ_ANNOTATION (genes.gtf)` terminated with an error exit status (1)


Command executed:

  dexseq_prepare_annotation.py genes.gtf DEXSeq.gff

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNASPLICE:RNASPLICE:DEXSEQ_DEU:DEXSEQ_ANNOTATION":
      htseq: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('htseq').version)")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  Traceback (most recent call last):
    File "/home/torres91/.nextflow/assets/nf-core/rnasplice/bin/dexseq_prepare_annotation.py", line 132, in <module>
      raise ValueError("Same name found on two strands: %s, %s" % (str(l[i]), str(l[i + 1])))
  ValueError: Same name found on two strands: <GenomicFeature: exonic_part 'Gm4312+Gm4301' at chr10: 100366498 -> 100367412 (strand '+')>, <GenomicFeature: e>

**Comment by jma1991** [comment]
> here is the last one: Reference genome options genome : mm10 fasta : s3://ngi-igenomes/igenomes//Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa gtf : s3://ngi-igenomes/igenomes//Mus_musculus/UCSC/mm10/Annotation/Genes/genes.gtf star_index : s3://ngi-igenomes/igenomes//Mus_musculus/UCSC/mm10/Sequence/STARIndex/ save_reference : true igenomes_base : s3://ngi-igenomes/igenomes/
> 
> Alignment options aligner : star_salmon
> 
> rMATS options rmats : true
> 
> DEXSeq DEU options dexseq_exon : true
> 
> edgeR DEU options edger_exon : true
> 
> DEXSeq DTU options dexseq_dtu : true min_samps_gene_expr : 4 min_samps_feature_expr: 2 min_samps_feature_prop: 2
> 
> Miso sashimi_plot : true miso_genes : ENSMUST00000105541.7,ENSMUST00000006787.7
> 
> ERROR ~ Error executing process > 'NFCORE_RNASPLICE:RNASPLICE:DEXSEQ_DEU:DEXSEQ_ANNOTATION (genes.gtf)'
> 
> Caused by: Process `NFCORE_RNASPLICE:RNASPLICE:DEXSEQ_DEU:DEXSEQ_ANNOTATION (genes.gtf)` terminated with an error exit status (1)
> 
> Command executed:
> 
> dexseq_prepare_annotation.py genes.gtf DEXSeq.gff
> 
> cat <<-END_VERSIONS > versions.yml "NFCORE_RNASPLICE:RNASPLICE:DEXSEQ_DEU:DEXSEQ_ANNOTATION": htseq: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('htseq').version)") END_VERSIONS
> 
> Command exit status: 1
> 
> Command output: (empty)
> 
> Command error: INFO: Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred INFO: Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred INFO: Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred Traceback (most recent call last): File "/home/torres91/.nextflow/assets/nf-core/rnasplice/bin/dexseq_prepare_annotation.py", line 132, in raise ValueError("Same name found on two strands: %s, %s" % (str(l[i]), str(l[i + 1]))) ValueError: Same name found on two strands: <GenomicFeature: exonic_part 'Gm4312+Gm4301' at chr10: 100366498 -> 100367412 (strand '+')>, <GenomicFeature: e>

This error comes from the dexseq_prepare_annotation.py script that comes with DEXSeq, so it's an issue with that script rather than the pipeline itself. I noticed that others have encountered the same issue, as discussed [here](https://stat.ethz.ch/pipermail/bioconductor/2012-June/046494.html) and [here](https://support.bioconductor.org/p/110990/) online. The suggested "fix" was either to avoid using the UCSC reference sequence and annotations or to modify the script to handle this edge case. If you'd like to tackle the script modification, I'm more than happy to accept pull requests! Meanwhile, I recommend using the Ensembl reference sequence and annotations as a workaround.

**Comment by torres-HI** [comment]
thank you

**Comment by jma1991** [comment]
Closing this issue. Feel free to re-open or make a new issue if you encounter another problem.
