### ISSUE TITLE
github API rate limit

### ISSUE THREAD

**Issue by KTMD-plant** [nf-core/rnasplice#153]
### Description of the bug

First of all thank you for developing this tool!

When running 

` nextflow pull nf-core/rnasplice      `

to install the rnasplice pipeline I get the following message. I get the following message. I don't think I should need to be logged in to download install the pipeline right?
The nf rnaseq pipeline is currently working for me.

WARN: Cannot read project manifest -- Cause: API rate limit exceeded -- Provide your GitHub user name and password to get a higher rate limit
API rate limit exceeded -- Provide your GitHub user name and password to get a higher rate limit

### Command used and terminal output

```console
nextflow pull nf-core/rnasplice

WARN: Cannot read project manifest -- Cause: API rate limit exceeded -- Provide your GitHub user name and password to get a higher rate limit
API rate limit exceeded -- Provide your GitHub user name and password to get a higher rate limit
```

### System information

 N E X T F L O W   ~  version 24.04.4

**Comment by jma1991** [comment]
Hello @KTMD-plant 

It looks like you may need to log in using your GitHub credentials. You can refer to a similar [issue](https://github.com/nextflow-io/nextflow/discussions/2459#discussioncomment-10033708) that was resolved in another nf-core pipeline for additional guidance.

**Comment by KTMD-plant** [comment]
Thanks for your quick response! I found a different solution: If you specify the version in the pull command you do not get this issue.

**Comment by jma1991** [comment]
No worries, glad your issues is resolved.
