### ISSUE TITLE
Is there a way to add --extra_salmon_quant_args to customize salmon run in the rnasplice

### ISSUE THREAD

**Issue by Motoufiq** [nf-core/rnasplice#162]
### Description of feature

Hi, I ran rnasplice pipeline (see below), and obtained outputs. Next, I am interested in performing isoform analysis on short read data (150bp) using the edgeR package, following the example from the edgeR User’s Guide, section: Refer: [4.6 Differential transcript expression of human lung adenocarcinoma cell lines](https://www.bioconductor.org/packages/devel/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf)

I wanted to try using the quant.sf files from the /salmon run by referring edgeR user guide, but I see there are NA values in the Overdispersion because I did not run with bootstrap/gibbs replicates in rnaplice run, [Salmon with inferential replicates](https://bioconductor.org/packages/devel/bioc/vignettes/tximport/inst/doc/tximport.html#Salmon_with_inferential_replicates): ? I there a way in the code to turn that on.

It seems adding `--numGibbsSamples 50` does fix what I am interested in. I tried adding `--extra_salmon_quant_args '--numGibbsSamples 50' \` to the run but the config file says invalid input. Does it makes sense to modify and  in [main.nf](https://github.com/nf-core/rnasplice/blob/master/modules/nf-core/salmon/quant/main.nf)

## main.nf

```
    """
    salmon quant \\
        --geneMap $gtf \\
        --threads $task.cpus \\
        --libType=$strandedness \\
        --numGibbsSamples 50 \\
        $reference \\
        $input_reads \\
        $args \\
        -o $prefix

    if [ -f $prefix/aux_info/meta_info.json ]; then
        cp $prefix/aux_info/meta_info.json "${prefix}_meta_info.json"
    fi

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        salmon: \$(echo \$(salmon --version) | sed -e "s/salmon //g")
    END_VERSIONS
    """
```

## nf-core rnasplice run submission script:

```
nextflow run /projects/toufim/nfcore_rnasplice/1_0_4/rnasplice \
--input /flashscratch/toufim/23_Palucka_003_004_samplesheet.csv \
--contrasts /flashscratch/toufim/23_Palucka_003_004_Contrastsheet.csv \
--outdir /flashscratch/toufim/ \
--fasta /projects/toufim/GENCODE/GRCh38.p14_Release_47/GRCh38.primary_assembly.genome.fa \
--gtf /projects/toufim/GENCODE/GRCh38.p14_Release_47/gencode.v47.primary_assembly.annotation.gtf \
--star_index /projects/STAR_INDEX/STAR_Index_GENCODE/hg38_sjdbOver_150_merged_gtf/ref/ \
--aligner star \
--gencode \
--gtf_extra_attributes gene_id \
--rmats_paired_stats false \
--rmats_read_len 151 \
--sashimi_plot false \
--dexseq_dtu false \
--extra_salmon_quant_args '--numGibbsSamples 50' \
-resume
```

**Comment by mirpedrol** [comment]
Cross-posting an answer from @ewels:

---

All nf-core pipelines can be run with any additional tool CLI flags, on a per-user basis without editing any pipeline code. See docs on how to do it [here](https://nf-co.re/docs/usage/getting_started/configuration#customising-tool-arguments).

In this case I think it would be a question of the OP setting this Nextflow config locally:

```nextflow
process {
    withName: 'SALMON_QUANT_SALMON' {
        ext.args = "--numGibbsSamples=50"
    }
}
```
If it's an argument that should be set for all pipeline users then it's best to create an issue on the pipeline's GitHub repo.

**Comment by Motoufiq** [comment]
@mirpedrol this is noted. Thank you very much.
