### ISSUE TITLE
dexseq: stager.R: subscript out of bounds.

### ISSUE THREAD

**Issue by gl9797** [nf-core/rnasplice#44]
### Description of the bug

Hey all, I had a package error:  'stager.R: subscript out of bounds.' when I was running rnasplice pipeline, it seems like stage-wise adjustment out of range in gene expression process. I'd be so thankful if anyone could provide some advices:

### Command used and terminal output

```console
nextflow run nf-core/rnasplice --input --outdir  -r dev --skip_alignment false  --rmats true --dexseq_exon true --edger_exon true --dexseq_dtu true-profile singularity --
```

### Relevant files

INFO:    Converting SIF file to temporary sandbox...
WARNING: Skipping mount /home/yl/.conda/envs/nf-core/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
Loading required package: SummarizedExperiment
Loading required package: MatrixGenerics
Loading required package: matrixStats
Attaching package: 'MatrixGenerics'
The following objects are masked from 'package:matrixStats':
    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars
Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel
Attaching package: 'BiocGenerics'
The following objects are masked from 'package:parallel':
    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB
The following objects are masked from 'package:stats':
    IQR, mad, sd, var, xtabs
The following objects are masked from 'package:base':
    Filter, Find, Map, Position, Reduce, anyDuplicated, append,
    as.data.frame, basename, cbind, colnames, dirname, do.call,
    duplicated, eval, evalq, get, grep, grepl, intersect, is.unsorted,
    lapply, mapply, match, mget, order, paste, pmax, pmax.int, pmin,
    pmin.int, rank, rbind, rownames, sapply, setdiff, sort, table,
    tapply, union, unique, unsplit, which.max, which.min
Loading required package: S4Vectors
Attaching package: 'S4Vectors'
The following object is masked from 'package:base':
    expand.grid
Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: Biobase
Welcome to Bioconductor
    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.
Attaching package: 'Biobase'
The following object is masked from 'package:MatrixGenerics':
    rowMedians
The following objects are masked from 'package:matrixStats':
    anyMissing, rowMedians
Attaching package: 'stageR'
The following object is masked from 'package:methods':
    getMethod
Error in `[<-`(`*tmp*`, idCon, 1, value = unlist(txLevelAdjustments)) : 
  subscript out of bounds
Calls: stageWiseAdjustment -> stageWiseAdjustment -> .local -> .stageWiseTest
Execution halted
INFO:    Cleaning up image...

### System information

Nextflow version (22.10.1)
256 cores 280GB
singularity
 ubuntu 22.04
 -r dev

**Comment by gl9797** [comment]
Used local genomo/gtf files downloaded form ucsc.

**Comment by jma1991** [comment]
Hey @gl9797 

This should be fixed in the latest development version. Please re-open if you are still having an issue and we'll investigate.
