### ISSUE TITLE
The default --miso_genes are invalid when --gencode is specified and cause the pipeline to fail

### ISSUE THREAD

**Issue by amizeranschi** [nf-core/rnasplice#78]
### Description of the bug

Basically what the title says. When running the pipeline with `--gencode`, the default value for `--miso_genes` should be `"ENSG00000004961.15, ENSG00000005302.19, ENSG00000147403.18"`, otherwise the pipeline will fail to run properly.

More info can be found here: https://github.com/nf-core/rnasplice/issues/72#issuecomment-1643637616

**Comment by valentinoruggieri** [comment]
Hey @amizeranschi , thank you for highlighting that. The problem refers to the gtf provided more than to the --gencode option. The pipeline has been designed to work with all the genomes and annotations, so we are going to fix that issue by changing some default options in the configuration file, leaving those IDs only for testing purpose.
