### ISSUE TITLE
The pipeline should be able to infer strandedness from FASTQ (i.e. allow "auto" for strandedness in the CSV)

### ISSUE THREAD

**Issue by amizeranschi** [nf-core/rnasplice#84]
### Description of feature

When running the pipeline from FASTQ files, the user currently needs to specify the strandedness as one of `unstranded`, `forward` or `reverse`, according to the documentation: https://nf-co.re/rnasplice/dev/docs/usage#samplesheet-input

It would be great to allow users to set this to `auto` and have the pipeline be able to infer strandedness automatically, the way `nf-core/rnaseq` does.

**Comment by jma1991** [comment]
Agreed, this would be a good feature to have. Will look at adding it for next release.

**Comment by amizeranschi** [comment]
Out of curiosity, if you're considering this feature for a next release, then why did you close this request as "not planned"?
