### ISSUE TITLE
example contrastsheet.csv missing

### ISSUE THREAD

**Issue by Kevin2197** [nf-core/rnasplice#93]
### Description of the bug

The link from the nf-core pipelines for the rnasplice contrastsheet: https://raw.githubusercontent.com/nf-core/rnasplice/dev/assets/contrastsheet.csv   is blank, it looks like it was deleted from the github page under /dev/assets/ could someone re upload the correct contrast sheet, as this is the part of the pipeline I keep getting errors for.

**Comment by jma1991** [comment]
Hi @Kevin2197 - The example data and metadata is now all in the test-datasets repository of the nf-core account. See here: https://github.com/nf-core/test-datasets/tree/rnasplice
