### ISSUE TITLE
Add some more tags to make the pipeline easier to find

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/rnasplice#97]
### Description of feature

Hey! The tags set on github are also displayed on the website and make it easier to find. would be nice to add a couple of relevant ones :) 
![Screenshot 2023-11-02 at 10 22 53](https://github.com/nf-core/rnasplice/assets/12273093/2ff3fdd2-4099-4193-bb4c-3892691fe05a)

**Comment by jma1991** [comment]
Hi @FriederikeHanssen - Thanks for letting us know about the missing tags. We've just added a few now, hopefully they are helpful to the community in finding the repository.
