### ISSUE TITLE
DRIMSEQ_FILTER error

### ISSUE THREAD

**Issue by DwinGrashof** [nf-core/rnasplice#98]
### Description of the bug

I am running rnasplice using the STAR mapping, and Salmon output files from the nf-core rnaseq pipeline. I presume, if I implement this in the nf-params file, rnaplice can work with the rnaseq output. I am getting the following error:
```
Command error:
  INFO:    Converting SIF file to temporary sandbox...
  WARNING: Skipping mount /home/lety/data/CBBI_Projects/general/software/miniconda3/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container

  Attaching package: 'DRIMSeq'

  The following object is masked from 'package:base':

      proportions

  Error in .local(x, ...) :
    min_samps_gene_expr >= 0 && min_samps_gene_expr <= ncol(x@counts) is not TRUE
  Calls: <Anonymous> -> <Anonymous> -> .local -> stopifnot
  Execution halted
  INFO:    Cleaning up image...
```
This is a similar error to the closed issue https://github.com/nf-core/rnasplice/issues/69
Where running this pipeline through conda or docker solved the problem. However, I can not deviate from using singularity. Are there other options to solve this error?
A commenter suggested that this is a known STAR 2.7.10a issue.
How can we proceed with this issue?

### Command used and terminal output

```console
nextflow \
	run nf-core/rnasplice \
	-r 1.0.0 \
	-profile singularity \
	--singularity_pull_docker_container \
	-name $runname \
	-params-file nf-params_rnasplice.json \
	-resume
```

### Relevant files

parameter file:
```
{
  "fasta": "/data/CBBI_Projects/SNRPA_Function/processed/dgrashof/snrpa_function/dgrashof/Nextflow/RNAseq_Salmon/genomes/GRCm39.primary_assembly.genome.fa",
  "gtf": "/data/CBBI_Projects/SNRPA_Function/processed/dgrashof/snrpa_function/dgrashof/Nextflow/RNAseq_Salmon/genomes/gencode.vM28.primary_assembly.annotation.gtf",
  "gencode": true,
  "save_reference": true,
  "save_unaligned": true,
  "save_align_intermeds": true,
  "aligner": "star_salmon",
  "extra_salmon_quant_args": "--incompatPrior 0.0",
  "max_cpus": 30,
  "skip_trimming": false,
  "trim_nextseq": 25,
  "deseq2_vst": true,
  "max_memory": "60.GB",
  "max_time": "168h",
  "save_trimmed": true,
  "pseudo_aligner": "salmon",
  "skip_bigwig": false,
  "skip_preseq": false,
  "skip_qualimap": false,
  "skip_dupradar": false,
  "skip_biotype_qc": false,
  "skip_markduplicates": false,
  "rseqc_modules": "bam_stat,inner_distance,infer_experiment,junction_annotation,junction_saturation,read_distribution,read_duplication,tin"
}
```

**Comment by bio-info-guy** [comment]
Upon isolating the run_drimseq_filter.R script in ./bin/ and running it on the specific input files and arguments, it would seem R does not recognize the filtering arguments as numerics, but rather as strings:

run_drimseq_filter.R: Line 27
min_samps_gene_expr    <- args[4]
min_samps_feature_expr <- args[5]
min_samps_feature_prop <- args[6]
min_feature_expr       <- args[7]
min_feature_prop       <- args[8]
min_gene_expr          <- args[9]

Thus comparisons later on fail, perhaps force the arguments into numbers will solve the problem. Weirdly enough, when I first installed the rnasplice pipeline and ran the test profile, everything worked.

**Comment by DwinGrashof** [comment]
I followed the same process, with running run_drimseq_filter.R myself, and when changing the class to numeric does solve the error, and when chancing the class to a character recreates the error "min_samps_gene_expr >= 0 && min_samps_gene_expr <= ncol(x@counts) is not TRUE" in the DRIMSeq::dmFilter function.

So the fix should be stating the class to numeric of the args in line 27.

**Comment by jma1991** [comment]
Hello @DwinGrashof 

Casting to numeric definitely seems like the correct fix. Could you also provide your nextflow.log and a snippet of the process which shows the command line which is run for run_drimseq_filter.R

Thanks!

**Comment by jma1991** [comment]
Hello @DwinGrashof and @bio-info-guy 

We have just generated a v1.0.1 release with the patch discussed above. Please give it a try and let us know if it has fixed your issue.

**Comment by DwinGrashof** [comment]
Dear @jma1991 ,

Patch v1.0.1 seems to have solved the `min_samps_gene_expr >= 0 && min_samps_gene_expr <= ncol(x@counts) is not TRUE` issue as expected.
I am running into another issue with stageR now, but I will post this first on the slack channel, and make a separate issue if necessary.

This issue can be closed, thanks a lot!
